@org_names = ["National Public Radio",
"Smithsonian Institute",
"Human Rights Campaign",
"Charity: water",
"Creative Commons",
"Kiva",
"World Food Program",
"UNICEF",
"Human Rights Watch",
"Feeding America",
"Metropolitan Museum of Art",
"Susan G Komen Breast Cancer Foundation",
"Sierra Club",
"Habitat for Humanity",
"Oxfam",
"American Red Cross",
"Do Something",
"Invisible Children",
"Save the Children",
"United States Olympic Committee",
"Best Friends Animal Society",
"Environmental Defense",
"Planned Parenthood",
"Rotary Foundation",
"ASPCA",
"Green Peace",
"American Heart Association",
"Samaritan's Purse",
"ACLU",
"The Trevor Project",
"St. Jude's Children's Research Hospital",
"International Rescue Committee",
"Teach for America",
"New York Public Library",
"Museum of Modern Art",
"American Museum of Natural History",
"Oxfam America",
"Wounded Warrior Project",
"World Wildlife Fund",
"Stand Up To Cancer",
"World Vision USA",
"Conservation International Foundation",
"Livestrong",
"Partners In Health",
"William J. Clinton Foundation",
"International Committee of the Red Cross",
"Oceana",
"Council on Foreign Relations",
"Natural Resources Defense Council",
"Water.org",
"Doctors Without Borders",
"Zoological Society of San Diego",
"Alzheimer's Association",
"Lions Clubs International Foundation",
"Compassion International",
"Mercy Corps",
"Goodwill",
"United States Fund for UNICEF",
"World Wildlife Fund",
"National 4-H Council",
"National Center for Missing and Exploited Children",
"Art Institute of Chicago",
"USO",
"Lincoln Center for Performing Arts",
"Humane Society of the United States",
"GlobalGiving",
"Ted Talks",
"Make-A-Wish America",
"Ashoka",
"Focus on the Family",
"Girl Scouts of the USA",
"Public Broadcasting Service",
"Monterey Bay Aquarium",
"Room to Read",
"The Center for Strategic and International Studies",
"Museum of Fine Arts Boston",
"Wikimedia Foundation",
"National Audubon Society",
"World Bank PNGO Project",
"United Nations High Commissioner for Refugees",
"Saint Louis Zoo Association",
"International Justice Mission",
"Dana-Farber Cancer Institute",
"Ronald McDonald House Charities",
"United Way",
"World Vision",
"Bill and Melinda Gates Foundation",
"Nature Conservancy",
"People for the Ethical Treatment of Animals",
"JFK Center for Performing Arts",
"WikiLeaks",
"National Council of YMCAs of the USA",
"PetSmart Charities",
"National Multiple Sclerosis Society",
"Defenders of Wildlife",
"CARE",
"The 92nd Street Y",
"Amnesty International USA",
"Free Software Foundation",
"Shedd Aquarium"]

@categories = ["Animal Rights, Welfare, and Services",
"Wildlife Conservation",
"Zoos and Aquariums",
"Arts, Culture, Humanities",
"Libraries, Historical Societies and Landmark Preservation",
"Museums",
"Performing Arts",
"Public Broadcasting and Media",
"Education",
"Universities, Graduate Schools, and Technological Institutes",
"Private Elementary and Secondary Schools",
"Other Education Programs and Services",
"Private Liberal Arts Colleges",
"Environment",
"Environmental Protection and Conservation",
"Botanical Gardens, Parks, and Nature Centers",
"Health",
"Diseases, Disorders, and Disciplines",
"Patient and Family Support",
"Treatment and Prevention Services",
"Medical Research",
"Human Services",
"Children's and Family Services",
"Youth Development, Shelter, and Crisis Services",
"Food Banks, Food Pantries, and Food Distribution",
"Multipurpose Human Service Organizations",
"Homeless Services",
"Social Services",
"International",
"Development and Relief Services",
"International Peace, Security, and Affairs",
"Humanitarian Relief Supplies",
"Single Country Support Organizations",
"Public Benefit",
"Advocacy and Civil Rights",
"Fundraising Organizations",
"Research and Public Policy Institutions",
"Community Foundations",
"Community and Housing Development"]
